### ISSUE TITLE
createdEpoch.toNumber() error with the library node-eventstore-client

### ISSUE THREAD

**Issue by juicycleff** [RemoteMetering/geteventstore-promise#77]
I fixed this issue and made a PR to node-eventstore-client. Hope it gets merged soon and I can upgrade the dependency here.

**Comment by mmuller99** [comment]
Hi @juicycleff, apologies for not being on the ball and checking the PR on the `node-eventstore-client` library.  I see it has been fixed [#91](https://github.com/nicdex/node-eventstore-client/issues/91). I've updated the deps.

Fixed with [#83](https://github.com/RemoteMetering/geteventstore-promise/pull/83)
